name: Finance Review Platform CI/CD

on:
  push:
    branches: [ main, develop, feature/feature-branch-1 ]  # Runs on push to main or develop or feature
  pull_request:
    branches: [ main, develop ]  # Runs on PRs

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on Linux

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Gets the latest code

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the latest stable Node.js

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Create environment.ts
        run: |
          cp src/environments/environment.ts.example src/environments/environment.ts
          sed -i 's#PLACEHOLDER_SECRET#'"${{ secrets.API_SECRET_KEY }}"'#g' src/environments/environment.ts
          sed -i 's#PLACEHOLDER_API_PREFIX1#'"${{ secrets.API_PREFIX1 }}"'#g' src/environments/environment.ts
          sed -i 's#PLACEHOLDER_API_PREFIX2#'"${{ secrets.API_PREFIX2 }}"'#g' src/environments/environment.ts

      - name: Build Angular App
        run: npm run build --configuration=production

      - name: 🔧 Install Firebase CLI
        run: npm install -g firebase-tools

      - name: 🚀 Deploy to Firebase Hosting
        if: github.ref == 'refs/heads/main'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only hosting --project render-report-api-b5ed1
